account/urls.py
from django.urls import path, include

from . import views 

app_name="account"
urlpatterns = [ 
    path('register', views.register_user, name="register_user"),
    path('', include('django.contrib.auth.urls'))

]

health_care_project/urls.py
 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls')),
    path('api/', include('predict.api.urls')),
    path('account/', include('account.urls')),
    
]

predict/api/urls.py
from django.urls import path 

from predict.api.views import prediction 


urlpatterns = [ 
    path('predict', prediction, name="prediction"),
    
]

predict/urls.py
from django.urls import path

from . import views 

app_name = "predict"
urlpatterns = [ 
    path('', views.index, name="index"),
    path('disease/<int:id>/detail', views.disease_detail, name="disease_detail"),


]

account/models.py
from django.db import models

# Create your models here.

predict/models.py
from django.db import models

# Create your models here.



class Symptom(models.Model):
    name = models.CharField(max_length = 50, unique=True)
    
    def __str__(self):
        return self.name 


class Disease(models.Model):
    name = models.CharField(max_length = 50, unique=True)
    description = models.TextField(null=True, blank=True)
    disease_symptom = models.ManyToManyField(Symptom, blank=True)
    prevention = models.TextField(default="")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def register_user(request):
    if request.method=="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New user created successfully !!!') 
            return redirect("account:login")
            
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

predict/api/views.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators import csrf
from django.views.decorators.csrf import csrf_exempt

from rest_framework.response import Response 
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
import io 

from .utility import make_prediction
from predict.models import Disease



# @csrf_exempt
@api_view(['POST'])
def prediction(request):
    if request.method=="POST":
        # print(request) 
        # print(type(request.data),request.data)

        # request.body
        """  byte_data = request.data 
        stream = io.BytesIO(byte_data) 
        python_data = JSONParser().parse(stream)  """
        
        python_data = request.data
        if len(python_data["data"])==0:
            msg = {"msg":"empty"}
        else: 
            prediction2 = make_prediction(python_data["data"]) 
            predicted_disease_description = list()
            for p in prediction2:
                disease = Disease.objects.get(name = p[0]) 
                predicted_disease_description.append({"id":disease.id, "name":disease.name, "description":disease.description,"percentage":p[1] }) 
            
            msg = {"msg":"success", "data": predicted_disease_description} 
        return JsonResponse(msg)
        # return Response(msg)

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
{%block style%} {% endblock %}
<meta charset="utf-8">
<meta http-equiv="	X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
</head>
<body>

{% include "header.html" %}
<div class="super_container">
    {% block content %}

    {% endblock %}

{% include "footer.html" %}
</div>


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'plugins/scrollTo/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/footer.html
{% load static %}
	<footer class="footer">
		<div class="parallax_background parallax-window" style="background-color: black; opacity: 0.5;" data-parallax="scroll" data-image-src="{%  static 'images/health4.jpg' %}" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter">
						<div class="newsletter_title_container text-center">
							<div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
							<div class="newsletter_subtitle">Join our database NOW!</div>
						</div>
						<div class="newsletter_form_container">
							<form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
								<div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
									<div><input type="text" class="newsletter_input newsletter_input_name" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
									<div><input type="email" class="newsletter_input newsletter_input_email" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div><button class="newsletter_button">subscribe</button></div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer_contact_row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/sign.svg' %}" alt=""></div>
								<div class="footer_contact_title">give us a call</div>
								<div class="footer_contact_list">
									<ul>
										<li>Office Landline: *********</li>
										<li>Mobile: **********</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/trekking.svg' %}" alt=""></div>
								<div class="footer_contact_title">come & drop by</div>
								<div class="footer_contact_list">
									<ul style="max-width:190px">
										<li>Ambition College, Kathmandu</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/around.svg' %}" alt=""></div>
								<div class="footer_contact_title">send us a message</div>
								<div class="footer_contact_list">
									<ul>
										<li>youremail@gmail.com</li>
										<li>Office@yourbusinessname.com</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i aria-hidden="true"></i> by <a href="#" target="_blank">Ambition Team</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>
	</footer>

templates/header.html
{% load static %}
	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
							<div class="logo"><a href="{% url 'predict:index'%}">HealthCare</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li class="active"><a href="{% url 'predict:index'%}">Home</a></li>
									<li><a href="/">About us</a></li>
									<li><a href="#">ALL disease</a></li>
									<li><a href="/">News</a></li>

									{% if request.user.is_authenticated %}		
										<li><a href="/">Feedback</a></li>
										<li><a href="{% url 'account:logout' %}">Logout</a></li>
									{% endif %}
								</ul>
							</nav>
							<div class="header_phone ml-auto">Call us: **********</div>

							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_social d-flex flex-row align-items-center justify-content-start">
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</header>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Hi {{ name }}</h1>

<form action="add" method="POST">
{% csrf_token %}

    Enter the First num :  <input type="number" name="num1"><br>
    Enter the Second num : <input type="number" name="num2"><br>
    <input type="submit"><br>
    Total : {{ result }}

</form>

{% endblock %}